<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WolverineFx" Version="3.9.0" />
    <PackageReference Include="FluentResults" Version="3.16.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FTDNA.Services.FamilyTreeV3.Common\FTDNA.Services.FamilyTreeV3.Common.csproj" />
  </ItemGroup>
</Project>
